service:
  local: ${DOWNLOADS}/Temp
spring:
  application:
    name: producer-consumer
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${postgresUser}
    password: ${postgresPassword}
    driver-class-name: org.postgresql.Driver
server:
  port: 8080